default_language_version:
    python: python3.8

default_stages: [commit, push]

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        types: [python]
        language: system